### PR TITLE
implemented new pub sub model

### PR DESCRIPTION
**Pull request by Engage-r**

### CODE REVIEW

**Comment by unniisme** [comment]
- Why isn't `Message.Data` of type `Data`? Since the message is serialized to encode the EventType by the networking module itself, shouldn't it be deserialized by the networking module too instead deserialization having to be done by the module that implements a reciever using `IEventHandler`?
- Isn't field `Message.ModuleName` redundant since it'll necessarily only be the value that we have subscribed for?
- Please comment public Interfaces such as `Events.IEventHandler`, `Serialization.ISerializer` and utilities such as `Utils.EventType` for ease of integration

**Comment by Engage-r** [comment]
# new pub sub model details:

- each module will subscribe with module Name, and a message handler function
- message will contain following fields:
	- source id
	- dest id
	- data
		- will contain event type
		- and payload to be sent
	- module Name -> will be directed to this module 
- each module will have their own event type contract
	- so if packet is directed to networking team then it will contain one of the events defined by networking team only.
- each module will give one message handler object only. Its upto the module to handle different event types within the same function itself.
- by this each module are free to have their own events
- networking team not dependent on any module

**Comment by Engage-r** [comment]
Each module will have its own event type. which they have to encode in their message. 
example message:
{
	ModuleName: "dashboard",
	DestId: "walter white",
	SourceId: "jessie",
	Data:"{
	EventType: "chatMessage",
	Payload:"your desired data here"
	}"
}

- Each module will have to pass "Data" as a serialized string . They have to implement their own serializer/des. for the Data . 
- The serializer is of networking module itself. No other module will be using that, anyways networking team is passing the Message object to the modules.

**Comment by Engage-r** [comment]
in send function moduleName parameter refers to the module to which the message will be sent to. Since the function is overloaded, if none is passed then it will be sent to the same module as the sender.

**Comment by Engage-r** [comment]
> 1. What event is received at the receiver when I simply send a string using the send function? Is it just `EventType.ChatMessage()` ?
> 
>     2. What should `IEventHandler.HandleMessageRecv` return?
> 
>     3. Why isn't `Message.Data` of type `Data`? Since the message is serialized to encode the EventType by the networking module itself, shouldn't it be deserialized by the networking module too instead deserialization having to be done by the module that implements a reciever using `IEventHandler`?
> 
>     4. Isn't field `Message.ModuleName` redundant since it'll necessarily only be the value that we have subscribed for?
> 
>     5. Please comment public Interfaces such as `Events.IEventHandler`, `Serialization.ISerializer` and utilities such as `Utils.EventType` for ease of integration

1. Pls read the new pub sub model details. In which I have mentioned that each module will have its own EventTypes. We won't be taking your eventtype in sender function, the serialzed message which you send to us may/may not contain your own defined eventtype.
2. Upto you, we return type as string so you could use it for debugging. We dont do anything with whatever you return.
3. NO pls go through the details, The Message obj does not contain any filed called as eventtype. The Data ( which contains the serialized message) may /may not contain it.
4. multiple modules will be subscribing on a client. you subscribe to message recvd not message sent.

**Comment by Engage-r** [comment]
Pls see **Program.cs in ClientApp** for example implementation.

**Pull request merged**
